name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Master
        uses: actions/checkout@v4
        with:
           ref: master
           path: master

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
           ref: gh-pages
           path: gh-pages

      - name: Set Version
        id: set-version
        working-directory: ./master
        run: |
          cat VERSION >> $GITHUB_OUTPUT

      - name: Zip Repository
        id: zip
        working-directory: ./master/src
        run: |
          zip ../JLCustomClock -9r *.lua *.txt
          cp ../JLCustomClock.zip ../../gh-pages

      - name: Setup Perl
        run: |
          sudo apt-get install -y libxml-simple-perl libdigest-sha-perl

      - name: Update SHA and Version in repo.xml
        id: tag
        working-directory: ./master
        run: |
          url="http://customclock.pcplayer.org"
          perl release.pl repo.xml ${{ steps.set-version.outputs.version }} JLCustomClock.zip $url

      - name: Update Master Repository
        working-directory: ./master
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add repo.xml
          git commit -m "Update repo.xml for release ${{ steps.set-version.outputs.version }}"
          git push origin HEAD:master

      - name: Update pages Repository
        working-directory: ./gh-pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add JLCustomClock.zip
          git commit -m "Update JLCustomClock for release ${{ steps.set-version.outputs.version }}"
          git push origin HEAD:gh-pages

